# generated by datamodel-codegen:
#   filename:  biblioteca_aneel_gov_br_legislacao_2016_metadados.json
#   timestamp: 2026-04-09T18:45:04+00:00

from __future__ import annotations

from datetime import date
from typing import Any, Dict, List

from pydantic import BaseModel, RootModel


class Model(RootModel[Any]):
    root: Dict[str, RegistroDiario]

class RegistroDiario(BaseModel):
    status: str
    registros: List[Registros]


class Registros(BaseModel):
    numeracaoItem: str
    titulo: str
    autor: str | None
    material: str
    esfera: str | None
    situacao: str | None
    assinatura: str | None
    publicacao: str
    assunto: str | None
    ementa: str | None
    pdfs: List[Pdf]

class Pdf(BaseModel):
    tipo: str
    url: str
    arquivo: str
    baixado: bool
